name: CI
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1
        with: 
          bun-version: 1.1.26
      - run: bun install
      - run: bun run typecheck
      - run: bun run lint
      - run: bun run test